name = "Perkpack: Big Globe"
author = "Blolol"
version = "1.0.0+1.21.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "355ae08c472a1e75ac0894a0f7b976fd0ba04ba5a002a8cd5fe9333904e001c4"

[versions]
fabric = "0.18.3"
minecraft = "1.21.10"
