name = "Perkpack: Big Globe"
author = "Blolol"
version = "1.0.0+1.21.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f585c1126585f6ad286e8a5c41568351ca40e769daebecd92dadf0c421dd3bdc"

[versions]
fabric = "0.18.3"
minecraft = "1.21.10"
