hash-format = "sha256"

[[files]]
file = "config/yosbr/config/MouseTweaks.cfg"
hash = "b317eebca4b559618fdfab00654abe556389369a81176b5638ade896af581400"

[[files]]
file = "config/yosbr/config/jei/jei-client.ini"
hash = "b7c690eee340378d8d33b36de6a58d2f68ebc6c8998322284c0279101427a42a"

[[files]]
file = "config/yosbr/config/journeymap-server.toml"
hash = "e9a9561e51dab88e12c261a7097788e1e3d6ba95c6035bdefa11cc91b4f50ab5"

[[files]]
file = "config/yosbr/config/ok_zoomer/config.json5"
hash = "8393f01d0e2368ee185bfaf3284bae2513d9818587cff92e189893feacbffbe4"

[[files]]
file = "config/yosbr/config/sodiumdynamiclights-client.toml"
hash = "001e45df23122651b3645821df31cf3ada9de4fa1bf8a75c377d45169c124fb2"

[[files]]
file = "config/yosbr/config/supplementaries-common.toml"
hash = "2a2b81a697b99f2d968294e43074908ec528926fd363b3bc8cdccdb575c674dc"

[[files]]
file = "config/yosbr/options.txt"
hash = "8231d6a6630b35dca0d330349aa3ba04965737291865faa77fea4b78d2ed505a"

[[files]]
file = "mods/accessories-compat-layer.pw.toml"
hash = "c255cf4cd29718e3ab0a4c18df8bb7b626e0092c5aad7b4e67f34fc1ad4492f8"
metafile = true

[[files]]
file = "mods/accessories.pw.toml"
hash = "19cbfb37dc29169b50599dfa328fe12a0ec9caaec8ac02627b5846f3bd9d1425"
metafile = true

[[files]]
file = "mods/accessorify.pw.toml"
hash = "69377da3eb02f91ca12ded74b9b7c10dee102635cf8b093fd30af992a208be0a"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
hash = "ca7ccbfc12a2103e8a155731eb03f94b243cc07fe9fae2f22c9ab04656109544"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "3b5f3feca8b299f947ed3956e49f7c3940793754928f2f99cad936448208a501"
metafile = true

[[files]]
file = "mods/athena-ctm.pw.toml"
hash = "9a9d6bf3715b20cbf83b967e4dd8b77972d1256e52a7b1c2bbfa4122f5acc931"
metafile = true

[[files]]
file = "mods/backport-copper-age.pw.toml"
hash = "61854b1ff0419be14d2a4fa1b70b382633e529a95b338c59fbd3f5c47ded96be"
metafile = true

[[files]]
file = "mods/backport-recipes.pw.toml"
hash = "55214ca943ee8cec11162b60cec3010fdd60dde0138de47c7c7bb87923d77061"
metafile = true

[[files]]
file = "mods/better-advancements.pw.toml"
hash = "93c4acd165a291c6d1e69c27b05b2747afc926b38a414712263fbc95f42da323"
metafile = true

[[files]]
file = "mods/better-animations-collection.pw.toml"
hash = "a97e9879873319e5f6731e48b430544461a43974029c99b9702a3c8245c88a7d"
metafile = true

[[files]]
file = "mods/better-clouds.pw.toml"
hash = "8169fa6b9fd786fcff725d88a4a3d344fecadb4abc2b2823c65af099d3a82147"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "68d6016fa3707c434b3aca5db041c7518c70feb53d0183faa2502cc6efd4c827"
metafile = true

[[files]]
file = "mods/c2me-neoforge.pw.toml"
hash = "c0c46fdc7e9ad31b975025a891abd5227562aae0107e79e8d8b6bb34acfa27a5"
metafile = true

[[files]]
file = "mods/chalk-mod.pw.toml"
hash = "92705ff84059ac0735eb0dac4eac6a6f7e03049d2eead27c0a127a7320410668"
metafile = true

[[files]]
file = "mods/cherished-worlds.pw.toml"
hash = "63f417eca4f251f85a5ae512394cbb9fa88dfdfb2b934b94637ba8b7dac1a831"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "24c6c3fe917ffbcef04e788dec3e003d0ed03433bc00f9cf4f23fe9b85636aa7"
metafile = true

[[files]]
file = "mods/clientsort.pw.toml"
hash = "3c6e7c5fb8aaa21f96941aac72aee623049e442d7b071e347118137fe49b7549"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "75181b55e0407d1fca1e2f346c6501f919f5109545990ddfb66db9cd1b771f8a"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "cde21d14fcaf9495f0f5b3d8fb298dd60cb12badc21a27414c25ebf11dfb3fe1"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
hash = "36f2f6e74b7dbeccb504572d47006582207544fa234a095093b97adfc7ecd5ac"
metafile = true

[[files]]
file = "mods/configured.pw.toml"
hash = "af4dc4828902eae1784568632a749fe9a442943f1570ac0ba3ea75e79934be41"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "8e5f6550359e71ecbea95705ec61fb03313550e6f481cabf48043929909aabae"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "36debf7653e95a855b4fedacc19027cf2e01960fc0b6d55ef2ffbffbcb455690"
metafile = true

[[files]]
file = "mods/cyanide.pw.toml"
hash = "08ab5ee502b94653263fdfea09b0c58958e9e6adffc45cb35f496cc5a0a6fb8d"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "61ce79aeecd3101399a33bbea16444736f2988b363a63c9f3b6a2c4fb0b3828a"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "ae6fd52d8bdcbeca5bbe6db840f22f92c1928fe0fda22017b19612b9b00a245a"
metafile = true

[[files]]
file = "mods/easy-anvils.pw.toml"
hash = "9f511e824978b45d8d90244e921dafcbb9bc01d1e4aced66afac71740ffa5ff6"
metafile = true

[[files]]
file = "mods/easy-magic.pw.toml"
hash = "1aa75105514780685caab9b945db2a2ea7c0594ced8c01e12f2a3e331f1af4e6"
metafile = true

[[files]]
file = "mods/enchanting-infuser.pw.toml"
hash = "6486106a7390a654715e158a5c59d804b69bf40a28736deb9a4f7742b811da06"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "c6d69011793e9278c65ba14423fccdbc2421f62676bad2663ba85ad9c386ae28"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "985b74e451dce434d27da73f711e365a874e7451220d574223555e888c518b1c"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "9a6f001c27c05b372f72ba0941e4904ab79fb7b1a9bd5944f9d41dc79cfb8ab1"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "73a8d2c9acc370851795fb46dae3b3cc25ffdbd045cfd793cbb7700fa78f7630"
metafile = true

[[files]]
file = "mods/euphoria-patches.pw.toml"
hash = "d2f3408511cbf4f8f2dcb5244e5cfdc8a1b8d14fc8a346d9f71756ec5c8d6fa7"
metafile = true

[[files]]
file = "mods/feature-recycler.pw.toml"
hash = "dfea23fdac9822913ae8f1c8751e9f0978ad4398ed8f9e45ca1a69c71025e979"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "73360e397134d238ee8fd21d33fd7f9275e9441f74f8f1b6ed92278877c0b9f1"
metafile = true

[[files]]
file = "mods/forge-cit.pw.toml"
hash = "5115aa2453a30675b9048bf7862e3193b43fc543ba27c3ecdebc44dce7bce2e5"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
hash = "9342bd3338c6fbb80f84625e2715a6c443b54daff11826f0dfb9ebb6ab411fd2"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "f9c118b7a66238a7f9e052705e82402e57c7a5b753d62d679b94701ede479752"
metafile = true

[[files]]
file = "mods/gravestone-mod.pw.toml"
hash = "2ac1df7fad83d36e69b4aaad32f0b952c9b039d7345592bb66934f40a8606224"
metafile = true

[[files]]
file = "mods/iceberg.pw.toml"
hash = "019fea93516a470bbcad284dd0cbad6f4e2914d96221c86e3f87c12fe6321e10"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "3d47b1d933d04934a606be1cbb67481860c3d68c9ed4efc387c7745d23b732a7"
metafile = true

[[files]]
file = "mods/infinity-water-bucket.pw.toml"
hash = "0363c8a19d850f64137780b03ed9302f1d27f12fee5527456cd4b1c2c04f53be"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "f67aa60c765593a8c70f78296a460349c6aef5f4a16d173eae02e8803b545ad4"
metafile = true

[[files]]
file = "mods/item-borders.pw.toml"
hash = "709a01e949975ef624c4fbeabb1d8a2339eb50709d2b3e1e84732ca31f341c4d"
metafile = true

[[files]]
file = "mods/jade-addons-forge.pw.toml"
hash = "8cd8400cb4e2c5ba60c8a359a7b6ff501078d2056eab0aba7f6b0ac77b7a0694"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "b6e0a61fea06f8d6d8e1672cf07b682625c4b74efd548d5093cd9c1fed167eec"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "5367193d3f87b7bc5a81bcd64a5b96a843e76d4df7a83c8bb7e1911aa82dd52e"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "b4c2535e950d602c2380cd83a32d5c5aa37f34d47aad63d30b46f144a9a89a89"
metafile = true

[[files]]
file = "mods/just-enough-resources-jer.pw.toml"
hash = "7905c08f37d8ebde50a5330a7dd10029de6259b0cb8adbde1170d93ea20218a7"
metafile = true

[[files]]
file = "mods/just-hammers.pw.toml"
hash = "af4465a52c59ed914f3b924bedb844cee7867b2682a356592aafb7246fd33427"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "27302b0087cf53570cd7a3b4eb550a208cbb6f6ba07210c604176155f39e0078"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "e7544296d2cdd85e43a60cf3e7a8f3e036782e14abc4efeea7f064d980d59dd5"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "40c53c83a10ed128decaa5975ee80e5431a8821b47862c625677d8e3fad289f6"
metafile = true

[[files]]
file = "mods/minecraftcapes.pw.toml"
hash = "6b49224791fb0bc84a9568d3d2c5b0c67eab1f5d1b7e4d07f372eb302e233fa0"
metafile = true

[[files]]
file = "mods/mod-menu-(neoforge-edition).pw.toml"
hash = "1a17dcb130a85f5fe951e5187d6e4ffcfcbf7e5c6bf9f6ccb453431c0692143e"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "6ae9430e2319ead3cb8580633c13d119c9d06f097204f3f8afbc0e4681e9a807"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "427e48f685c2af70f0fda07648073379f3b343436b038c7289d98c56b55c322c"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "91696791780719730cb8826de0c53d8513a7c2b320f7d641dbeb6ca974e5cec3"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "6bc414cc0f2d4c078fe83f384d786343f701f371d657c5279b5b0df1595804bd"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "5da18814472be5dc93a21886983646da3a7236413800075ac75229be82d114fa"
metafile = true

[[files]]
file = "mods/ok-zoomer.pw.toml"
hash = "8a5b280bcfbbb9a6682108d873ad152737f4cc1bc34d0c30be4714039ca19bf2"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "46831c04077a06df823bcd0f254833a90a9a9ccc78f5069f4b4c27fa301ac0cf"
metafile = true

[[files]]
file = "mods/particular-reforged.pw.toml"
hash = "86a9a547931b50ca0d9716912f2858e15b05e71e3359f40f0667994c2e28c9d2"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "880e51166c531f473f9bdef251a6c42c6d13f4283bcc8e27d66999aef57c9a59"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
hash = "c99c5bac469e8d6ece5aae80f08635e3bbb8367f0c586b6288573c725faefe69"
metafile = true

[[files]]
file = "mods/prism-lib.pw.toml"
hash = "d9b38ba42434eb436d036b1c8add839bee003240dc85cc54ec626aac58c59070"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "6812c3faa178cd48c65c5b8e7aeef50bc0b63d8e3b2117065d6179a43d8d3649"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "09306b955060349986ccf6a6d2a67f1e019fa172a7dc690dd6007f81c966309a"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "27721caca5a03b743bf25888e1d984142948069dace31453f103f94f7f24d2ce"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "c0b066684294c33972d562e0cb08ea17b2d31bcf86cd1d6c63b8e968f0eac7a2"
metafile = true

[[files]]
file = "mods/sodium-dynamic-lights.pw.toml"
hash = "c1e526d3d17cb3563e596d45c7567ed1fe60c31bdc3457f7a747ef8150bd3c1b"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "a1fb713df668ed21dda0602e99cb23b991c8faff841e130d7aae46258c3d6a45"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "d193173f0f5dfb4a921d44e29e8d5cee656dd3a40872939069715bb482b66fc9"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0281ed9713f3141bdac363056a791845510e14761ea65b4b2813cf96d664b20a"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "765832eca01cad73acbfac6ed74cb0169cc14ca6c9e7c9b5396cd2d7bdaa547c"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "5569b0e47ee6ef3cc89609bc93bbec46bb023153be244510069f37209cd8ab13"
metafile = true

[[files]]
file = "mods/sophisticated-storage.pw.toml"
hash = "16877075dea15e77a180907b82c69500cf9ce5e9e64f9fde89f3163fcaf47e86"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "258a77de0a6db4c9ab045cbb240bcf4eac0dbbca3f6bc981fb461e55c247f23f"
metafile = true

[[files]]
file = "mods/storagedrawers.pw.toml"
hash = "1d277d4c4d8f3abc49176d3b029584b70d92dcb9b89cf2cf6094e674fe9885c8"
metafile = true

[[files]]
file = "mods/structure-layout-optimizer.pw.toml"
hash = "27fbafdc78a4a3cb8badb58078ec1f2837e65a5bbe5160e344b0fb3e779c9efe"
metafile = true

[[files]]
file = "mods/supplemental-patches.pw.toml"
hash = "30a8b719ae854c7d457a37ff539a1310ad6e4afaa9c4ffafe680b05e2835d4fd"
metafile = true

[[files]]
file = "mods/supplementaries-squared.pw.toml"
hash = "91ebbd7b58f32ec3cf848d203b70ef193675585d6b761de912afdd977ed5f84b"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "c6182c863ef7758553bc7ad14b8b111e094bd7feda60793e4c656cd9a225fce4"
metafile = true

[[files]]
file = "mods/toms-storage.pw.toml"
hash = "c743ea0e4f9021ef5f2fd093006e04031da11b933a0a54d86ef77bc13f4965cb"
metafile = true

[[files]]
file = "mods/trading-post.pw.toml"
hash = "72c0db4d726a16d80c2337cc9dc4d220ba8298deb5db5d9d58082d15a245ea3f"
metafile = true

[[files]]
file = "mods/travelersbackpack.pw.toml"
hash = "93c6836527aaf36bcae2619268d73271b81b053a92e8c043c7963d4bf24af22c"
metafile = true

[[files]]
file = "mods/tree-harvester.pw.toml"
hash = "f5b816b8de8c237a6a7b51fda8323627a995796589fc6934ed4cd15e7f40e55a"
metafile = true

[[files]]
file = "mods/universal-sawmill.pw.toml"
hash = "c41f6ccffb66b9095efabea4eda10dd61bdb375cbeccbab638b3c139c1b00161"
metafile = true

[[files]]
file = "mods/veinmining.pw.toml"
hash = "f2f23f33862c06cbf23683f034c34c8dfa4580d716a3f385fc3053ceda725087"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "539f362e9e192cf3b2813e0dfdfc51a5e6814129c6e82a9733842529beea6242"
metafile = true

[[files]]
file = "mods/yeetus-experimentus.pw.toml"
hash = "5e25dccab496945a5f19bb82383e0ebf98452ffc14cd25c7e0259cc44312281a"
metafile = true

[[files]]
file = "mods/yosbr-neo.pw.toml"
hash = "a735706c28aaf07cf3283f2d17727798b8af815e40fafb4d3fc2d279132ea1a2"
metafile = true

[[files]]
file = "shaderpacks/bliss-shader.pw.toml"
hash = "8ffd81a5e0b4c3bc2daf0d86714ef56df4beb1ed87a5c41c4e9bbb94a7006bc1"
metafile = true

[[files]]
file = "shaderpacks/bsl-shaders.pw.toml"
hash = "015b33a9619d0a9ce18bc30b0a06dbb388b7d8ba0f24d63b4bc3db88bdb25101"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "b769a2f7ef2fa754224c5068491e79d02c0c85e0bc326fc05247f18315cc866b"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
hash = "5caf93fa1624aeb26d11cdbadcb0c03b2a92815c798a930014774c7d525baf28"
metafile = true

[[files]]
file = "shaderpacks/photon-shader.pw.toml"
hash = "3add1378e964947556ec43ebc86a431981cfa67c9b95353105d7f48deb58ff3d"
metafile = true
