name = "Perkpack"
author = "Ross Paffett"
version = "5.0.0-pre0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c02da0cf04ca7df2c7361ccfc531fac1a38ae7da23040f0c4343569033848cb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
