name = "Perkpack"
author = "Ross Paffett"
version = "5.0.0-pre0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc944b0e4a71ed32b19d2d87ffdbdd033ec9b949ef4cedbc4487225d9ff62d20"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
